# site settings
theme: jekyll-theme-architect
locale                   : "en-US"
title                    : "Zhaocheng / Leo's Homepage"
title_separator          : "-"
name                     : &name "Leo"
description              : &description "personal description"
url                      : https://zhaochengli.github.io # the base hostname & protocol for your site
repository               : "ZhaochengLi/ZhaochengLi.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
words_per_minute         : 160
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts

# Social Sharing
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : linkedin
  name                   : Zhaocheng Li
  links                  : www.linkedin.com/in/zhaocheng-leo

# site Author
author:
  name             : "Zhaocheng Li (Leo)"
  avatar           : "profile.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Victoria, BC, CANADA"
  employer         : "University of Victoria"
  email            : "leolee0706@gmail.com"
  url              : "https://zhaochengli.github.io"
  github           : "https://zhaochengli.github.io"
  linkedin         : "https://www.linkedin.com/in/zhaocheng-leo"
