# Site Settings
theme                    : "jekyll-theme-cayman"
locale                   : "en-US"
highlighter              : "rouge"
title                    : name"/Leo's Homepage"
title_separator          : "-"
name                     : &name "Zhaocheng Li"
description              : &description "Zhaocheng Li, UVic, BSc, Major CS&Math, Major Stats"
url                      : https://zhaochengli.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository               : "ZhaochengLi/ZhaochengLi.github.io"
